name: braveai
trust: braveai
profile: braveai
storage:
  type: zfs
  name: braveai
  size: 15GB
network:
  name: braveaibr0
  ip: 30.0.0.1
backendsettings:
  type: lxd
  resources:
    name: ""
    os: ""
    cpu: ""
    ram: ""
    hd: ""
    ip: 127.0.0.1
status: inactive
