services:
  python-base:
    bravefile: ./base/Bravefile
    #build: true
    base: true
  api:
    bravefile: ./api/Bravefile
    build: true
    depends_on:
      - python-base 
      - auth
      - log
  auth:
    bravefile: ./auth/Bravefile
    build: true
    depends_on:
      - python-base
      - log
  log:
    bravefile: ./log/Bravefile
    build: true
    depends_on:
      - python-base
